version: "3"
services:
   birdnet-0:
      container_name: "bai-birdnet-0"
      image: birdnet-public-3k-v2.2:latest
      restart: always
      ipc: host
      ports:
         - "7100:6000"
      volumes:
         - ${DATA_DIRECTORY}:/mnt/data
         - ${RESULT_DIRECTORY}:/mnt/result
      environment:
         - OVERLAP=1
