# docker-compose.yml
version: "3"
services:
   birdid-0:
      container_name: "bai-birdid-0"
      image: birdid-europe254-2103-flask-v04
      restart: always
      runtime: nvidia
      ipc: host
      environment:
         NVIDIA_VISIBLE_DEVICES: "0"
         NVIDIA_DRIVER_CAPABILITIES: "all"
      ports:
         - "9000:4000"
      volumes:
         - ${MDAS_DATA_DIRECTORY}:/mnt/data
         - ${MDAS_RESULT_DIRECTORY}:/mnt/result
   birdid-1:
      container_name: "bai-birdid-1"
      image: birdid-europe254-2103-flask-v04
      restart: always
      runtime: nvidia
      ipc: host
      environment:
         NVIDIA_VISIBLE_DEVICES: "1"
         NVIDIA_DRIVER_CAPABILITIES: "all"
      ports:
         - "9001:4000"
      volumes:
         - ${MDAS_DATA_DIRECTORY}:/mnt/data
         - ${MDAS_RESULT_DIRECTORY}:/mnt/result
