# docker-compose.yml
version: "3"
services:
   backend:
      image: mdas-backend
      build: ./backend
      ports:
         - "8000:80"
      depends_on:
         - db
      environment:
         MARIADB_HOST: db
         MARIADB_DATABASE: ${MARIADB_DATABASE}
         MARIADB_PORT: ${MARIADB_PORT}
         MARIADB_USER: ${MARIADB_USER}
         MARIADB_PASSWORD: ${MARIADB_PASSWORD}
         TMP_DIRECTORY: /tmp
         SAMPLE_FILES_DIRECTORY: /files
         PROXY_PATH_PREFIX: /api/v1
         ROOT_PATH: /api/v1
         REPORTS_DIRECTORY: /reports
      volumes:
         - ${SAMPLE_FILES_DIRECTORY}:/files
         - ${TMP_DIRECTORY}:/tmp
         - ${DATA_DIRECTORY}:${DATA_DIRECTORY}
         - ${REPORTS_DIRECTORY}:/reports

   frontend:
      image: mdas-frontend
      build: ./frontend
      ports:
         - "80:80"
   db:
      container_name: "bai-mariadb"
      image: mariadb:10
      restart: always
      environment:
         MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
         MARIADB_DATABASE: "${MARIADB_DATABASE}"
         MARIADB_USER: "${MARIADB_USER}"
         MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      ports:
         - "${MARIADB_PORT}:3306"
      volumes:
         - ./runtime-data/db-data/data:/var/lib/mysql
         - ./runtime-data/db-data/conf:/etc/mysql
