services:
   backend:
      image: mdas-backend
      build: ./backend
      ports:
         - "8000:80"
      depends_on:
         - db
      environment:
         POSTGRES_HOST: db
         POSTGRES_DATABASE: ${POSTGRES_DB}
         POSTGRES_PORT: ${POSTGRES_PORT}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         TMP_DIRECTORY: /tmp
         SAMPLE_FILES_DIRECTORY: /files
         PROXY_PATH_PREFIX: /ecomon/api/v1
         ROOT_PATH: /ecomon/api/v1
         REPORTS_DIRECTORY: /reports
      volumes:
         - ${SAMPLE_FILES_DIRECTORY}:/files
         - ${TMP_DIRECTORY}:/tmp
         - ${DATA_DIRECTORY}:${DATA_DIRECTORY}
         - ${REPORTS_DIRECTORY}:/reports
      labels:
         - "traefik.http.routers.backend.rule=PathPrefix(`/ecomon/api/v1`)"
         - "traefik.http.routers.backend.entrypoints=web"
         - "traefik.http.routers.backend.middlewares=strip-prefix@docker"
         - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/ecomon/api/v1"
         - "traefik.http.services.backend.loadbalancer.server.port=80"

   frontend:
      image: mdas-frontend
      build: ./frontend
      ports:
         - "8001:80"
      labels:
         - "traefik.http.routers.frontend.rule=PathPrefix(`/ecomon`)"
         - "traefik.http.routers.frontend.entrypoints=web"
         - "traefik.http.services.frontend.loadbalancer.server.port=80"

   db:
      image: postgres:16
      restart: always
      environment:
         POSTGRES_DB: "${POSTGRES_DATABASE}"
         POSTGRES_USER: "${POSTGRES_USER}"
         POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
         POSTGRES_ROOT_PASSWORD: "${POSTGRES_ROOT_PASSWORD}"
      ports:
         - "${POSTGRES_PORT}:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data
         - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

   traefik:
      image: traefik:v2.10
      command:
         - "--api.insecure=true"
         - "--providers.docker=true"
         - "--entrypoints.web.address=:80"
      ports:
         - "80:80"
         - "8080:8080" # Traefik dashboard
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      labels:
         - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
         - "traefik.http.routers.traefik.rule=PathPrefix(`/traefik`)"
         - "traefik.http.routers.traefik.entrypoints=web"
         - "traefik.http.routers.traefik.service=api@internal"
         - "traefik.http.routers.traefik.middlewares=auth"
volumes:
   postgres_data:
