# docker-compose.yml
version: "3"
services:

  frontend: 
    image: bai/database
    build: ./frontend
  db:
    container_name: "bai-mariadb"
    image: mariadb/server:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${BAI_MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${BAI_MARIADB_DATABASE}"
      MARIADB_USER: "${BAI_MARIADB_USER}"
      MARIADB_PASSWORD: "${BAI_MARIADB_PASSWORD}"
    ports:
      - "${BAI_MARIADB_PORT}:3306"
    volumes:
      - ./db-data/data:/var/lib/mysql
      - ./db-data/conf:/etc/mysql
  birdid-0:
    container_name: "bai-birdid-0"
    image: birdid-europe254-2103-flask-v04
    restart: always
    runtime: nvidia
    ipc: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "9000:4000"
    volumes:
      - ${BAI_DATA_DIRECTORY}:/mnt/data
      - ${BAI_RESULT_DIRECTORY}:/mnt/result
  birdid-1:
    container_name: "bai-birdid-1"
    image: birdid-europe254-2103-flask-v04
    restart: always
    runtime: nvidia
    ipc: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "1"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "9001:4000"
    volumes:
      - ${BAI_DATA_DIRECTORY}:/mnt/data
      - ${BAI_RESULT_DIRECTORY}:/mnt/result
  birdid-2:
    container_name: "bai-birdid-2"
    image: birdid-europe254-2103-flask-v04
    restart: always
    runtime: nvidia
    ipc: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "2"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "9002:4000"
    volumes:
      - ${BAI_DATA_DIRECTORY}:/mnt/data
      - ${BAI_RESULT_DIRECTORY}:/mnt/result

  birdid-3:
    container_name: "bai-birdid-3"
    image: birdid-europe254-2103-flask-v04
    restart: always
    runtime: nvidia
    ipc: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "9003:4000"
    volumes:
      - ${BAI_DATA_DIRECTORY}:/mnt/data
      - ${BAI_RESULT_DIRECTORY}:/mnt/result
  birdid-4:
    container_name: "bai-birdid-4"
    image: birdid-europe254-2103-flask-v04
    restart: always
    runtime: nvidia
    ipc: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "1"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "9004:4000"
    volumes:
      - ${BAI_DATA_DIRECTORY}:/mnt/data
      - ${BAI_RESULT_DIRECTORY}:/mnt/result
  birdid-5:
    container_name: "bai-birdid-5"
    image: birdid-europe254-2103-flask-v04
    restart: always
    runtime: nvidia
    ipc: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "2"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "9005:4000"
    volumes:
      - ${BAI_DATA_DIRECTORY}:/mnt/data
      - ${BAI_RESULT_DIRECTORY}:/mnt/result

  birdid-6:
    container_name: "bai-birdid-6"
    image: birdid-europe254-2103-flask-v04
    restart: always
    runtime: nvidia
    ipc: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "9006:4000"
    volumes:
      - ${BAI_DATA_DIRECTORY}:/mnt/data
      - ${BAI_RESULT_DIRECTORY}:/mnt/result
  birdid-7:
    container_name: "bai-birdid-7"
    image: birdid-europe254-2103-flask-v04
    restart: always
    runtime: nvidia
    ipc: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "1"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "9007:4000"
    volumes:
      - ${BAI_DATA_DIRECTORY}:/mnt/data
      - ${BAI_RESULT_DIRECTORY}:/mnt/result
  birdid-8:
    container_name: "bai-birdid-8"
    image: birdid-europe254-2103-flask-v04
    restart: always
    runtime: nvidia
    ipc: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "2"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "9008:4000"
    volumes:
      - ${BAI_DATA_DIRECTORY}:/mnt/data
      - ${BAI_RESULT_DIRECTORY}:/mnt/result
