version: "3"
services:
   db:
      image: postgres:16
      restart: always
      environment:
         POSTGRES_DB: "${POSTGRES_DATABASE}"
         POSTGRES_USER: "${POSTGRES_USER}"
         POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
         POSTGRES_ROOT_PASSWORD: "${POSTGRES_ROOT_PASSWORD}"
      ports:
         - "${POSTGRES_PORT}:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data
         - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
   postgres_data:
