# docker-compose.yml
version: "3"
services:
  backend:
    image: bai-backend
    build: ./backend
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      BAI_MARIADB_HOST: db
      BAI_MARIADB_DATABASE: ${BAI_MARIADB_DATABASE}
      BAI_MARIADB_PORT: ${BAI_MARIADB_PORT}
      BAI_MARIADB_USER: ${BAI_MARIADB_USER}
      BAI_MARIADB_PASSWORD: ${BAI_MARIADB_PASSWORD}
      BAI_TMP_DIRECTORY: /tmp
      BAI_SAMPLE_FILE_DIRECTORY: /files
      BAI_PROXY_PATH_PREFIX: /api/v1
      ROOT_PATH: /api/v1
    volumes:
      - ./runtime-data/backend/files:/files
      - ./runtime-data/backend/tmp:/tmp
      - /net:/net

  frontend:
    image: bai-frontend
    build: ./frontend
    ports:
      - "80:80"
  db:
    container_name: "bai-mariadb"
    image: mariadb:10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${BAI_MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${BAI_MARIADB_DATABASE}"
      MARIADB_USER: "${BAI_MARIADB_USER}"
      MARIADB_PASSWORD: "${BAI_MARIADB_PASSWORD}"
    ports:
      - "${BAI_MARIADB_PORT}:3306"
    volumes:
      - ./runtime-data/db-data/data:/var/lib/mysql
      - ./runtime-data/db-data/conf:/etc/mysql
