# docker-compose.yml
version: "3"
services:
   backend:
      image: mdas-backend
      build: ./backend
      ports:
         - "8000:80"
      depends_on:
         - db
      environment:
         MDAS_MARIADB_HOST: db
         MDAS_MARIADB_DATABASE: ${MDAS_MARIADB_DATABASE}
         MDAS_MARIADB_PORT: ${MDAS_MARIADB_PORT}
         MDAS_MARIADB_USER: ${MDAS_MARIADB_USER}
         MDAS_MARIADB_PASSWORD: ${MDAS_MARIADB_PASSWORD}
         MDAS_TMP_DIRECTORY: /tmp
         MDAS_SAMPLE_FILE_DIRECTORY: /files
         MDAS_PROXY_PATH_PREFIX: /api/v1
         ROOT_PATH: /api/v1
      volumes:
         - ${MDAS_SAMPLE_FILE_DIRECTORY}:/files
         - ${MDAS_TMP_DIRECTORY}:/tmp
         - ${MDAS_DATA_DIRECTORY}:${MDAS_DATA_DIRECTORY}

   frontend:
      image: mdas-frontend
      build: ./frontend
      ports:
         - "80:80"
   db:
      container_name: "bai-mariadb"
      image: mariadb:10
      restart: always
      environment:
         MARIADB_ROOT_PASSWORD: "${MDAS_MARIADB_ROOT_PASSWORD}"
         MARIADB_DATABASE: "${MDAS_MARIADB_DATABASE}"
         MARIADB_USER: "${MDAS_MARIADB_USER}"
         MARIADB_PASSWORD: "${MDAS_MARIADB_PASSWORD}"
      ports:
         - "${MDAS_MARIADB_PORT}:3306"
      volumes:
         - ./runtime-data/db-data/data:/var/lib/mysql
         - ./runtime-data/db-data/conf:/etc/mysql
