query listDataDirectories($subpath: String = "") {
  data: listDataDirectories(subpath: $subpath) {
    name
    path
  }
}

mutation createVoucherSamples(
  $modelId: Int!
  $siteId: Int!
  $labelIds: [Int]!
  $sampleCount: Int!
  $startDatetime: String!
  $endDatetime: String!
  $audioPaddingMs: Int!
  $highPassFilterFrequencyHz: Int!
) {
  data: createVoucherSamples(
    createVoucherRequestInput: {
      modelId: $modelId
      siteId: $siteId
      labelIds: $labelIds
      sampleCount: $sampleCount
      startDatetime: $startDatetime
      endDatetime: $endDatetime
      audioPaddingMs: $audioPaddingMs
      highPassFilterFrequencyHz: $highPassFilterFrequencyHz
    }
  ) {
    jobId
  }
}
