fragment Job on jobs {
  id
  status
  topic
  metadata
  result
  progress
  error
  updated_at
  created_at
}
query getJobsPagniated(
  $limit: Int = 10
  $offset: Int = 0
  $order_by: [jobs_order_by!] = { id: desc }
  $where: jobs_bool_exp = {}
) {
  items: jobs(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    ...Job
  }
  total: jobs_aggregate(where: $where) {
    aggregate {
      count
    }
  }
}

query getSiteJobsByTopic($siteId: Int!, $_or: [jobs_bool_exp!]!) {
  data: jobs(
    where: { _and: { _or: $_or, metadata: { _contains: { site_id: $siteId } } } }
    order_by: { created_at: desc }
  ) {
    ...Job
  }
}
