subscription subscribeActiveJobs {
  jobs(order_by: { id: desc }, where: { status: { _nin: ["done", "failed"] } }) {
    id
    status
    topic
    metadata
    result
    progress
    error
    updated_at
    created_at
  }
}
