http:
  routers:
    frontend:
      entryPoints:
        - web
      rule: host(`{{env "DOMAIN"}}`) && PathPrefix(`{{env "SUB_PATH"}}`)
      service: frontend


  services:
    frontend:
      loadBalancer:
        servers:
          - url: http://frontend:3000
