http: 
  routers:
    hasura:
      entryPoints:
        - web
      rule: host(`{{env "DOMAIN"}}`) && PathPrefix(`{{env "SUB_PATH"}}/api/v1/graphql`)
      service: hasura
      middlewares:
        - hasura
        - remove-auth-headers
  services:
    hasura:
      loadBalancer:
        servers:
        - url: http://graphql-engine:8080
  middlewares:
    hasura:
      stripPrefix:
        prefixes:
        - {{env "SUB_PATH"}}/api
    remove-auth-headers:
      headers:
        customRequestHeaders:
          Authorization: ""